<a href="https://colab.research.google.com/github/ntuyen610/Practice_with_Python/blob/main/Day_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [6]:
# Use zeros function: Ex: np.zeros(shape)

print(np.zeros((3,4)))

print(torch.zeros((3,4)))

print(tf.zeros((3,4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [7]:
# Use ones function: Ex: np.ones(shape)

print(np.ones((3,4)))

print(torch.ones((3,4)))

print(tf.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [8]:
# Use full()/ fill() function: Ex: np.full(shape, value)


print(np.full((3,4),5))

print(torch.full((3,4),5))

print(tf.fill((3,4), 5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
