<a href="https://colab.research.google.com/github/ntuyen610/Practice_with_Python/blob/main/Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array (Numpy):**
- là cấu trúc dữ liệu đa chiều
- giúp lưu trữ + thực hiện các phép toán trên dữ liệu số
- Có thể là mảng 0/1/2/ nhiều chiều

**Tensor (Pytorch/Tensorflow)**
- cấu trúc dữ liệu nhiều chiều
- được thiết kế tương thích với học sâu
- trên các thiết bị GPU/ TPU
- tensors là đơn cị cơ bản để lưu trữ và xử lí dữ liệu


In [1]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
#Create 1 list 1D
lst_1D = list(range(1,10))
lst_1D

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#Create 1 array 1D from list
arr_1D = np.array(lst_1D)
arr_1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Create 1 tensor PyTorch 1D from list
tensor_1D_pt = torch.tensor(lst_1D)
tensor_1D_pt

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Create 1 tensor TensorFlow from list
tensor_1D_tf = tf.convert_to_tensor(lst_1D)
tensor_1D_tf

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [10]:
#Create list 2D
list_2D = [
    [1,2,3],
    [2,4,6],
    [8,9,10]
]
#Create array 2D
arr_2D = np.array(list_2D)

print(arr_2D.shape)
print(arr_2D.dtype)
print(type(arr_2D))

(3, 3)
int64
<class 'numpy.ndarray'>


In [13]:
#create Pytorch 2D
tensor_2D_pt = torch.tensor(list_2D)

print(tensor_2D_pt.shape)
print(tensor_2D_pt.dtype)
print(type(tensor_2D_pt))
#Thiet bi luu tru cuar tensor
print(tensor_2D_pt.device)

torch.Size([3, 3])
torch.int64
<class 'torch.Tensor'>
cpu


In [14]:
#create tensor TensorFlow 2D
tensor_2D_tf = tf.convert_to_tensor(list_2D)

print(tensor_2D_tf.shape)
print(tensor_2D_tf.dtype)
print(type(tensor_2D_tf))
print(tensor_2D_tf.device)

(3, 3)
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
/job:localhost/replica:0/task:0/device:CPU:0
